apiVersion: apps/v1

kind: Deployment

metadata:

  name: docker-deployment

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-deployment
        role: rolling-update 
  



    spec:

      containers:

      - name: docker-deployment

        image: chanxxx1999/docker-spring-boot:v2

        ports:

        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /
            port: 8090

    strategy:
      type: RollingUpdate
      rollingUp      maxSurge: 50%         

---

apiVersion: v1

kind: Service

metadata:

  name: docker-deployment

spec:

  type: NodePort

  selector:

    app: docker-deployment

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8090

