apiVersion: apps/v1

kind: Deployment

metadata:

  name: docker-deployment

spec:
   

  selector:
    replicas: 1

    matchLabels:

      app: docker-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailabe: 1
  minReadySeconds: 5
   
  template:

    metadata:

      labels:

        app: docker-deployment

    spec:
      
         
      containers:

      - name: docker-deployment

        image: chanxxx1999/docker-spring-boot:latest
        imagePullPolicy: Always  

        ports:
            - containerPort: 8090
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTPS
            path: /
            httpHeaders:
            - name: Host
              value: myhost
            port: 8090      
           
         

---

apiVersion: v1

kind: Service

metadata:

  name: docker-deployment

spec:

  type: NodePort

  selector:

    app: docker-deployment

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8090



