apiVersion: apps/v1

kind: Deployment

metadata:

  name: docker-deployment

spec:
 strategy:
 type: RollingUpdate
 rollingUpdate:
  maxSurge: 3
  maxUnavailabe: 1
  imeoutSeconds: 100
  intervalSeconds: 5
  updatePeriodSeconds: 5    

  selector:

    matchLabels:

      app: docker-deployment

  replicas: 1

  template:

    metadata:

      labels:

        app: docker-deployment

    spec:

      containers:

      - name: docker-deployment

        image: chanxxx1999/docker-spring-boot

        ports:

        - containerPort: 8090

---

apiVersion: v1

kind: Service

metadata:

  name: docker-deployment

spec:
strategy:
 type: RollingUpdate
 rollingUpdate:
  maxSurge: 3
  maxUnavailabe: 1
  imeoutSeconds: 100
  intervalSeconds: 5
  updatePeriodSeconds: 5





  type: NodePort

  selector:

    app: docker-deployment

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8090
